### PR TITLE
Migrate to Null Safety

### PR DESCRIPTION
**Pull request by michalt**
This migrates the code to Null Safety. I've tried to split it into a few commits to make it clear what hints were necessary and what was automatically inferred by the migration tool.
Let me know what you think about!

(I've tested this with `pub run --enable-experiment=non-nullable test` and will test in google3)

### CODE REVIEW

**Review by bkonyi — COMMENTED** [review]
Thanks for migrating this! Just curious, did you use the HTTP implementation in `dart:io` as a base for this? If I recall correctly, this code is almost identical to the non-sync implementation, so we'll probably want to confirm that these signatures match those of their non-sync counterparts.

**Comment by michalt** [comment]
Do you mean the implementations of the `HttpHeaders` interface from `dart:io`? If so, then yes -- I've used `dart:io` that is already null safe so we should be compatible with it. (but please do double check if you see something suspicious ;)

**Comment by bkonyi** [comment]
LGTM, but it looks like we'll need to update the Travis config. Would you mind removing the [2.0.0 entries](https://github.com/dart-lang/sync_http/blob/master/.travis.yml#L8) here? I don't think we need to be testing directly against 2.0.0 anymore... :-)

**Comment by michalt** [comment]
Thanks! I've updated the Travis config and pubspec (I basically followed what other dart-lang packages have been doing) and everything seems to work :)

**Comment by bkonyi** [comment]
Awesome! Thanks for doing this :-) Do you know when this should be published to pub?

**Comment by michalt** [comment]
@bkonyi IIUC we need to wait until Null Safety is released (@jakemac53 is that accurate? Thanks!)

**Comment by jakemac53** [comment]
It can be published to pub once the tests/analyzer can pass without the flag - so either once it is added to the allow list (not planned at this time) or the feature is released and the min sdk is bumped to the version in which it was released.

**Pull request merged**
