### PR TITLE
prep for publishing

### PR DESCRIPTION
**Pull request by devoncarew**
Prep for publishing:

- switch to using package:lints
- update the readme markdown badges
- adjust the usage guidance in the readme a bit - highlight that people should generally be using package:http

Publishing will let us capture the above changes as well as a previous change to the pubspec repository field.

### CODE REVIEW

**Comment by devoncarew** [comment]
cc @bkonyi @kevmoo

**Review by bkonyi — APPROVED** [review]

**Comment by bkonyi** [comment]
LGTM, but I can't merge.

**Comment by devoncarew** [comment]
From the history, it seems like you're one of the main contributors? We should set you up w/ write access to this repo.

**Comment by bkonyi** [comment]
> From the history, it seems like you're one of the main contributors? We should set you up w/ write access to this repo.

Yes, I wrote the package years ago :-) No idea why I never had merge permissions, but probably didn't question it as an L3 5 years ago.

**Pull request merged**
